"""
Git agent: creates a branch, commits the approved diff, and opens a GitHub PR.

Requires GITHUB_TOKEN and GITHUB_REPO (owner/repo) in the environment.
If either is absent the node completes successfully without creating a PR —
the caller can inspect state["pr_url"] to see whether one was created.

GitHub operations use the REST API via httpx (already a dependency).
No local git clone required.
"""

from __future__ import annotations

import os
import re
import textwrap
from datetime import UTC, datetime

import httpx
from dotenv import load_dotenv

from src.agents.tools import BASE_FILES
from src.sandbox.runner import get_patched_files
from src.state import AgentMessage, AgentState

load_dotenv()

_BASE = "https://api.github.com"
_DEFAULT_BRANCH = "main"


def _headers() -> dict[str, str]:
    return {
        "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _slugify(text: str, max_len: int = 40) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower().strip())
    return slug[:max_len].strip("-")


def _build_pr_body(state: AgentState) -> str:
    plan = state["plan"]
    review = state["review_feedback"]
    test = state["test_result"]

    test_section = "Not run."
    if test:
        status_line = "PASSED" if test.passed else f"FAILED (exit {test.exit_code})"
        last_line = (test.stdout.strip().splitlines() or [""])[-1]
        test_section = f"{status_line}\n```\n{last_line}\n```"

    return textwrap.dedent(f"""\
        ## Summary
        {state["feature_request"]}

        ## Implementation
        {plan.reasoning if plan else "N/A"}

        ## Pipeline stats
        - Review iterations: {state["iteration_count"]}
        - Debug iterations: {state["debug_count"]}
        - Review verdict: {review.summary if review else "N/A"}

        ## Test results
        {test_section}

        ---
        *Generated by [multi-agent-code](https://github.com) · {datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")}*
    """)


def _get_base_sha(client: httpx.Client, repo: str, branch: str) -> str:
    r = client.get(f"{_BASE}/repos/{repo}/git/ref/heads/{branch}", headers=_headers())
    r.raise_for_status()
    return r.json()["object"]["sha"]


def _get_tree_sha(client: httpx.Client, repo: str, commit_sha: str) -> str:
    r = client.get(f"{_BASE}/repos/{repo}/git/commits/{commit_sha}", headers=_headers())
    r.raise_for_status()
    return r.json()["tree"]["sha"]


def _create_blob(client: httpx.Client, repo: str, content: str) -> str:
    r = client.post(
        f"{_BASE}/repos/{repo}/git/blobs",
        headers=_headers(),
        json={"content": content, "encoding": "utf-8"},
    )
    r.raise_for_status()
    return r.json()["sha"]


def _create_tree(client: httpx.Client, repo: str, base_tree: str, blobs: list[dict]) -> str:
    r = client.post(
        f"{_BASE}/repos/{repo}/git/trees",
        headers=_headers(),
        json={"base_tree": base_tree, "tree": blobs},
    )
    r.raise_for_status()
    return r.json()["sha"]


def _create_commit(
    client: httpx.Client, repo: str, message: str, tree_sha: str, parent_sha: str
) -> str:
    r = client.post(
        f"{_BASE}/repos/{repo}/git/commits",
        headers=_headers(),
        json={"message": message, "tree": tree_sha, "parents": [parent_sha]},
    )
    r.raise_for_status()
    return r.json()["sha"]


def _create_branch(client: httpx.Client, repo: str, branch: str, sha: str) -> None:
    r = client.post(
        f"{_BASE}/repos/{repo}/git/refs",
        headers=_headers(),
        json={"ref": f"refs/heads/{branch}", "sha": sha},
    )
    r.raise_for_status()


def _create_pr(
    client: httpx.Client, repo: str, title: str, body: str, head: str, base: str
) -> str:
    r = client.post(
        f"{_BASE}/repos/{repo}/pulls",
        headers=_headers(),
        json={"title": title, "body": body, "head": head, "base": base},
    )
    r.raise_for_status()
    return r.json()["html_url"]


def git_agent_node(state: AgentState) -> dict:
    if state["status"] == "rejected":
        return {
            "messages": [AgentMessage(role="planner", content="Run rejected by human reviewer.")],
        }

    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPO")

    if not token or not repo:
        return {
            "status": "pr_created",
            "messages": [
                AgentMessage(
                    role="planner",
                    content=(
                        "GITHUB_TOKEN / GITHUB_REPO not set — skipping PR creation. "
                        "Apply the diff manually."
                    ),
                )
            ],
        }

    # Get patched file contents to commit.
    patched_files, err = get_patched_files(state["current_diff"] or "", BASE_FILES)
    if err:
        return {
            "status": "pr_created",
            "messages": [AgentMessage(role="planner", content=f"Patch failed: {err}")],
        }

    feature_slug = _slugify(state["feature_request"])
    branch_name = f"ai-codegen/{feature_slug}"
    pr_title = f"feat: {state['feature_request'][:70]}"
    commit_msg = f"feat: {state['feature_request'][:70]}\n\nGenerated by multi-agent-code pipeline."

    with httpx.Client(timeout=30) as client:
        base_sha = _get_base_sha(client, repo, _DEFAULT_BRANCH)
        base_tree_sha = _get_tree_sha(client, repo, base_sha)

        blobs = [
            {
                "path": path,
                "mode": "100644",
                "type": "blob",
                "sha": _create_blob(client, repo, content),
            }
            for path, content in patched_files.items()
        ]

        new_tree_sha = _create_tree(client, repo, base_tree_sha, blobs)
        new_commit_sha = _create_commit(client, repo, commit_msg, new_tree_sha, base_sha)
        _create_branch(client, repo, branch_name, new_commit_sha)
        pr_url = _create_pr(
            client,
            repo,
            title=pr_title,
            body=_build_pr_body(state),
            head=branch_name,
            base=_DEFAULT_BRANCH,
        )

    return {
        "git_branch": branch_name,
        "pr_url": pr_url,
        "status": "pr_created",
        "messages": [AgentMessage(role="planner", content=f"PR opened: {pr_url}")],
    }
